# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - master

pool:
  vmImage: ubuntu-latest

steps:
  - script: echo Hello, world!!
    displayName: "Run a one-line script"

  - script: |
      echo "----------------"
      echo $(Build.SourceBranch)
      echo $(Build.SourceBranchName)
      echo $(Build.Reason)
      echo $(Build.QueuedBy)
      echo $(Environment.Name)
      echo $(Environment.ResourceName)
      echo $(System.PullRequest.SourceBranch)
      echo $(System.PullRequest.TargetBranch)
      echo $(Build.SourceVersionMessage)
      echo "---------------"
    displayName: "Run a multi-line script"

  - script: |
      gh api \
      -H "Accept: application/vnd.github+json" \
      /repos/tomashornak/country-flag-icons/pulls/2/comments
    displayName: "Run a one-line script"
